[build-system]
requires = [
  "wheel",
  "setuptools>=45",
  "setuptools_scm[toml]>=6.0",
]

[tool.setuptools_scm]
local_scheme = "dirty-tag"

[tool.black]
line-length = 88

[tool.isort]
multi_line_output = 3
profile = "black"
